# Generated by Django 5.2.15 on 2026-06-11 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_alter_church_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('department', 'Department'), ('fellowship', 'Fellowship'), ('cell', 'Cell'), ('church', 'Church-wide')], default='church', max_length=20)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('expected_attendee_count', models.IntegerField(blank=True, null=True)),
                ('head_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(blank=True, db_column='cell_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='org.cell')),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='org.church')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='org.department')),
                ('fellowship', models.ForeignKey(blank=True, db_column='fellowship_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='org.fellowship')),
                ('recorded_by', models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_events', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.attendanceevent')),
            ],
            options={
                'db_table': 'attendance_events',
                'ordering': ['-event_date', '-event_time'],
            },
        ),
    ]
