# Generated by Django 5.2.15 on 2026-06-11 19:37

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('org', '0002_alter_church_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('department', 'Department'), ('fellowship', 'Fellowship'), ('cell', 'Cell'), ('church', 'Church-wide')], default='church', max_length=20)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('recurrence_type', models.CharField(choices=[('none', 'No recurrence'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('recurrence_day_of_week', models.IntegerField(blank=True, help_text='0=Mon .. 6=Sun', null=True)),
                ('recurrence_week_position', models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('last', 'Last')], max_length=10, null=True)),
                ('recurrence_day_of_month', models.IntegerField(blank=True, null=True)),
                ('event_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(blank=True, default=90, null=True)),
                ('default_location', models.TextField(blank=True, null=True)),
                ('active_from', models.DateField(default=datetime.date.today)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(blank=True, db_column='cell_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_templates', to='org.cell')),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.PROTECT, related_name='event_templates', to='org.church')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_templates', to='org.department')),
                ('fellowship', models.ForeignKey(blank=True, db_column='fellowship_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_templates', to='org.fellowship')),
            ],
            options={
                'db_table': 'event_templates',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='template',
            field=models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_events', to='events.eventtemplate'),
        ),
        migrations.CreateModel(
            name='RecurrenceException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(blank=True, db_column='cancelled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='events.eventtemplate')),
            ],
            options={
                'db_table': 'recurrence_exceptions',
                'unique_together': {('template', 'exception_date')},
            },
        ),
    ]
