# Generated by Django 5.2.15 on 2026-06-12 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventtemplate_alter_attendanceevent_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='attendance_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='attendance_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='attendance_closed_by',
            field=models.ForeignKey(blank=True, db_column='attendance_closed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_registers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='attendance_reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='attendance_reopened_by',
            field=models.ForeignKey(blank=True, db_column='attendance_reopened_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_registers', to=settings.AUTH_USER_MODEL),
        ),
    ]
