# Generated by Django 5.2.15 on 2026-06-12 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0003_churchsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_code', models.TextField()),
                ('is_income', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to='org.church')),
            ],
            options={
                'db_table': 'finance_accounts',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_code', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.financeaccount')),
            ],
            options={
                'db_table': 'finance_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.TextField()),
                ('quote_currency', models.TextField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('effective_from', models.DateTimeField()),
                ('source', models.TextField(blank=True, null=True)),
                ('zone_unit_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(blank=True, db_column='church_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_snapshots', to='org.church')),
            ],
            options={
                'db_table': 'currency_snapshots',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['church', 'base_currency', 'quote_currency', '-effective_from'], name='currency_sn_church__7d6492_idx')],
            },
        ),
    ]
