# Generated by Django 5.2.15 on 2026-06-12 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_access_level'),
        ('finance', '0001_initial'),
        ('org', '0003_churchsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collected_at_church', models.BooleanField(default=True)),
                ('collected_at_unit_type', models.CharField(blank=True, max_length=20, null=True)),
                ('pledge_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.TextField()),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('received_date', models.DateField()),
                ('payment_method', models.TextField(blank=True, null=True)),
                ('reference_number', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_multi_currency', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('submitted_by', models.UUIDField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('voided_by', models.UUIDField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to='finance.financeaccount')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='finance.financecategory')),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='org.church')),
                ('collected_at_cell', models.ForeignKey(blank=True, db_column='collected_at_cell_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.cell')),
                ('collected_at_department', models.ForeignKey(blank=True, db_column='collected_at_department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.department')),
                ('collected_at_fellowship', models.ForeignKey(blank=True, db_column='collected_at_fellowship_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.fellowship')),
                ('member', models.ForeignKey(blank=True, db_column='member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='accounts.member')),
            ],
            options={
                'db_table': 'income_records',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeCurrencyAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('rate_effective_from', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('income_record', models.ForeignKey(db_column='income_record_id', on_delete=django.db.models.deletion.CASCADE, related_name='currency_amounts', to='finance.incomerecord')),
            ],
            options={
                'db_table': 'income_currency_amounts',
            },
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['church', 'status'], name='income_reco_church__82f248_idx'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['account', 'received_date'], name='income_reco_account_37860e_idx'),
        ),
    ]
