# Generated by Django 5.2.15 on 2026-06-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_incomerecord_incomecurrencyamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerecord',
            name='espees_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
