# Generated by Django 5.2.15 on 2026-06-12 14:26

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_member_ministry_group_memberidsequence'),
        ('org', '0002_alter_church_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('parent_of', 'Parent of'), ('spouse_of', 'Spouse of')], max_length=20)),
                ('parent_type', models.CharField(blank=True, choices=[('biological', 'Biological'), ('adoptive', 'Adoptive'), ('step', 'Step')], max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('divorced', 'Divorced'), ('widowed', 'Widowed'), ('annulled', 'Annulled')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_member', models.ForeignKey(db_column='from_member_id', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='accounts.member')),
                ('to_member', models.ForeignKey(db_column='to_member_id', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='accounts.member')),
            ],
            options={
                'db_table': 'family_relationships',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.CASCADE, related_name='households', to='org.church')),
                ('head_member', models.ForeignKey(blank=True, db_column='head_member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads_households', to='accounts.member')),
            ],
            options={
                'db_table': 'households',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_to_head', models.CharField(choices=[('head', 'Head'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('grandchild', 'Grandchild'), ('dependent', 'Dependent'), ('other', 'Other')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(db_column='household_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.household')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to='accounts.member')),
            ],
            options={
                'db_table': 'household_members',
            },
        ),
        migrations.CreateModel(
            name='MemberSpouseLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_a', models.ForeignKey(db_column='member_a_id', on_delete=django.db.models.deletion.CASCADE, related_name='spouse_links_a', to='accounts.member')),
                ('member_b', models.ForeignKey(db_column='member_b_id', on_delete=django.db.models.deletion.CASCADE, related_name='spouse_links_b', to='accounts.member')),
            ],
            options={
                'db_table': 'member_spouse_links',
            },
        ),
    ]
