# Generated by Django 5.2.15 on 2026-06-10 19:05

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user_custom',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_code', models.TextField()),
                ('title', models.TextField(blank=True, null=True)),
                ('surname', models.TextField()),
                ('other_names', models.TextField()),
                ('preferred_name', models.TextField(blank=True, null=True)),
                ('academic_title', models.TextField(blank=True, null=True)),
                ('maiden_name', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20, null=True)),
                ('phone_primary', models.TextField(blank=True, null=True)),
                ('phone_whatsapp', models.TextField(blank=True, null=True)),
                ('telegram_username', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, default='Ghana', null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('employer', models.TextField(blank=True, null=True)),
                ('baptism_status', models.CharField(blank=True, choices=[('not_baptized', 'Not baptized'), ('baptized_water', 'Baptized (water)'), ('baptized_holy_spirit', 'Baptized (Holy Spirit)'), ('both', 'Both')], default='not_baptized', max_length=30, null=True)),
                ('born_again_date', models.DateField(blank=True, null=True)),
                ('foundation_school_status', models.CharField(choices=[('not_enrolled', 'Not enrolled'), ('enrolled', 'Enrolled'), ('completed', 'Completed')], default='not_enrolled', max_length=20)),
                ('foundation_school_completion_date', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('official_photo_path', models.TextField(blank=True, null=True)),
                ('display_photo_path', models.TextField(blank=True, null=True)),
                ('official_photo_updated_at', models.DateTimeField(blank=True, null=True)),
                ('display_photo_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_reason', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(blank=True, db_column='cell_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='org.cell')),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.PROTECT, related_name='members', to='org.church')),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_level', models.CharField(choices=[('member', 'Member'), ('counter', 'Counter'), ('unit_leader', 'Unit leader'), ('treasurer', 'Treasurer'), ('admin', 'Admin'), ('group_pastor', 'Group pastor'), ('zonal_pastor', 'Zonal pastor'), ('super_admin', 'Super admin'), ('church_pastor', 'Church pastor')], default='member', max_length=20)),
                ('preferred_language', models.TextField(blank=True, default='en', null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(blank=True, db_column='church_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='org.church')),
                ('member', models.ForeignKey(blank=True, db_column='member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='accounts.member')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
