# Generated by Django 5.2.15 on 2026-06-10 21:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp'),
        ('org', '0002_alter_church_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ministry_group',
            field=models.ForeignKey(blank=True, db_column='ministry_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='org.ministrygroup'),
        ),
        migrations.CreateModel(
            name='MemberIdSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fellowship_code', models.TextField()),
                ('year', models.IntegerField()),
                ('last_seq', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.CASCADE, related_name='id_sequences', to='org.church')),
            ],
            options={
                'db_table': 'member_id_sequences',
                'unique_together': {('church', 'fellowship_code', 'year')},
            },
        ),
    ]
