# Generated by Django 5.2.15 on 2026-06-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_ministry_group_memberidsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.CharField(choices=[('member', 'Member'), ('counter', 'Counter'), ('unit_leader', 'Unit leader'), ('treasurer', 'Treasurer'), ('admin', 'Admin'), ('group_pastor', 'Group pastor'), ('zonal_pastor', 'Zonal pastor'), ('super_admin', 'System Administrator'), ('church_pastor', 'Church pastor')], default='member', max_length=20),
        ),
    ]
