# Generated by Django 5.2.15 on 2026-06-10 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_code', models.TextField()),
                ('display_name', models.TextField(blank=True, null=True)),
                ('member_id_template', models.TextField(default='{CHURCH_CODE}-{YEAR}-{SEQ:00000}')),
                ('default_currency', models.TextField(default='GHS')),
                ('timezone', models.TextField(default='Africa/Accra')),
                ('city', models.TextField(blank=True, null=True)),
                ('planted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='inactive', max_length=10)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planted_from_church', models.ForeignKey(blank=True, db_column='planted_from_church_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='org.church')),
            ],
            options={
                'db_table': 'churches',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_code', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='org.church')),
                ('parent_department', models.ForeignKey(blank=True, db_column='parent_department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='org.department')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='EcclesiasticalUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('zone', 'Zone'), ('group', 'Group')], max_length=20)),
                ('name', models.TextField()),
                ('short_code', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_church', models.ForeignKey(blank=True, db_column='head_church_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heads_units', to='org.church')),
                ('parent_unit', models.ForeignKey(blank=True, db_column='parent_unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='org.ecclesiasticalunit')),
            ],
            options={
                'db_table': 'ecclesiastical_units',
            },
        ),
        migrations.AddField(
            model_name='church',
            name='parent_unit',
            field=models.ForeignKey(blank=True, db_column='parent_unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='churches', to='org.ecclesiasticalunit'),
        ),
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_code', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_day', models.TextField(blank=True, null=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.CASCADE, related_name='fellowships', to='org.church')),
                ('parent_department', models.ForeignKey(db_column='parent_department_id', on_delete=django.db.models.deletion.CASCADE, related_name='fellowships', to='org.department')),
            ],
            options={
                'db_table': 'fellowships',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_code', models.TextField()),
                ('location_description', models.TextField(blank=True, null=True)),
                ('meeting_day', models.TextField(blank=True, null=True)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fellowship', models.ForeignKey(db_column='fellowship_id', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='org.fellowship')),
            ],
            options={
                'db_table': 'cells',
            },
        ),
        migrations.CreateModel(
            name='MinistryGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('short_code', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.CASCADE, related_name='ministry_groups', to='org.church')),
            ],
            options={
                'db_table': 'ministry_groups',
            },
        ),
    ]
