# Generated by Django 5.2.15 on 2026-06-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'verbose_name_plural': 'churches'},
        ),
    ]
