# Generated by Django 5.2.15 on 2026-06-12 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_alter_church_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('church', models.OneToOneField(db_column='church_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='org.church')),
                ('sms_api_key', models.TextField(blank=True, null=True)),
                ('sms_sender_id', models.TextField(blank=True, null=True)),
                ('sms_dev_mode', models.BooleanField(blank=True, null=True)),
                ('smtp_host', models.TextField(blank=True, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_user', models.TextField(blank=True, null=True)),
                ('smtp_password', models.TextField(blank=True, null=True)),
                ('smtp_from_email', models.TextField(blank=True, null=True)),
                ('smtp_from_name', models.TextField(blank=True, null=True)),
                ('smtp_secure', models.BooleanField(blank=True, null=True)),
                ('require_income_approval', models.BooleanField(blank=True, default=True, null=True)),
                ('display_currencies', models.JSONField(blank=True, default=list, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_member_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'church_settings',
            },
        ),
    ]
