# Generated by Django 5.2.15 on 2026-06-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_churchsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='allow_self_approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
