# Generated by Django 5.2.15 on 2026-06-12 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_email', models.TextField(blank=True, null=True)),
                ('table_name', models.TextField()),
                ('row_id', models.UUIDField()),
                ('action', models.TextField()),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('church_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table_name', 'row_id'], name='audit_log_table_n_65e433_idx'), models.Index(fields=['church_id'], name='audit_log_church__756f13_idx')],
            },
        ),
    ]
