# Generated by Django 5.2.15 on 2026-06-12 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_alter_church_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayCardTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image_path', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('zones', models.JSONField(default=list)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo_x', models.IntegerField(default=40)),
                ('photo_y', models.IntegerField(default=40)),
                ('photo_size', models.IntegerField(default=300)),
                ('photo_circle', models.BooleanField(default=True)),
                ('name_x', models.IntegerField(default=40)),
                ('name_y', models.IntegerField(default=360)),
                ('name_size', models.IntegerField(default=64)),
                ('message_x', models.IntegerField(default=40)),
                ('message_y', models.IntegerField(default=440)),
                ('message_size', models.IntegerField(default=36)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=9)),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.CASCADE, related_name='birthday_templates', to='org.church')),
            ],
            options={
                'db_table': 'birthday_card_templates',
                'ordering': ['name'],
            },
        ),
    ]
