# Generated by Django 5.2.15 on 2026-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaycardtemplate',
            name='text_stroke',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='birthdaycardtemplate',
            name='text_stroke_width',
            field=models.IntegerField(default=3),
        ),
    ]
