# Generated by Django 5.2.15 on 2026-06-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0002_birthdaycardtemplate_text_stroke_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaycardtemplate',
            name='message_font',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='birthdaycardtemplate',
            name='name_font',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
