# Generated by Django 5.2.15 on 2026-06-11 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_member_ministry_group_memberidsequence'),
        ('org', '0002_alter_church_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=20)),
                ('scope_type', models.TextField()),
                ('scope_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='accounts.member')),
            ],
            options={
                'db_table': 'member_roles',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_leader', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('can_announce_own_cell', models.BooleanField(default=False)),
                ('can_announce_own_fellowship', models.BooleanField(default=False)),
                ('can_announce_own_department', models.BooleanField(default=False)),
                ('can_announce_any_cell', models.BooleanField(default=False)),
                ('can_announce_any_fellowship', models.BooleanField(default=False)),
                ('can_announce_any_department', models.BooleanField(default=False)),
                ('can_announce_whole_church', models.BooleanField(default=False)),
                ('can_announce_leaders_only', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(db_column='church_id', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='org.church')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(blank=True, db_column='cell_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='org.cell')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='org.department')),
                ('fellowship', models.ForeignKey(blank=True, db_column='fellowship_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='org.fellowship')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.member')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='access.role')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
    ]
