# Generated by Django 5.2.15 on 2026-06-12 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='rank',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='UnitRoleApplicability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_type', models.CharField(max_length=20)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='applicabilities', to='access.role')),
            ],
            options={
                'db_table': 'unit_role_applicability',
                'unique_together': {('role', 'unit_type')},
            },
        ),
    ]
