# Generated by Django 5.2.15 on 2026-06-12 10:35

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_ministry_group_memberidsequence'),
        ('attendance', '0002_eventexpectedattendee'),
        ('events', '0003_attendanceevent_attendance_closed_and_more'),
        ('org', '0002_alter_church_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_first_time', models.BooleanField(default=True)),
                ('visitor_type', models.CharField(choices=[('first_time', 'First time'), ('returning', 'Returning'), ('special_guest', 'Special guest')], default='first_time', max_length=20)),
                ('responded_to_alter_call', models.BooleanField(default=False)),
                ('alter_call_notes', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('visitor', 'Visitor'), ('first_timer', 'First timer'), ('follow_up', 'Follow-up'), ('integrated', 'Integrated'), ('member', 'Member')], default='first_timer', max_length=20)),
                ('post_service_followup_done', models.BooleanField(default=False)),
                ('stage_first_timer_at', models.DateTimeField(blank=True, null=True)),
                ('stage_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('stage_integrated_at', models.DateTimeField(blank=True, null=True)),
                ('stage_member_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_cell', models.ForeignKey(blank=True, db_column='assigned_cell_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.cell')),
                ('assigned_fellowship', models.ForeignKey(blank=True, db_column='assigned_fellowship_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.fellowship')),
                ('converted_to_member', models.ForeignKey(blank=True, db_column='converted_to_member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_visitor', to='accounts.member')),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='events.attendanceevent')),
                ('follow_up_member', models.ForeignKey(blank=True, db_column='follow_up_member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following_up_visitors', to='accounts.member')),
                ('invited_by_member', models.ForeignKey(blank=True, db_column='invited_by_member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_visitors', to='accounts.member')),
            ],
            options={
                'db_table': 'attendance_visitors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FirstTimerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_date', models.DateField(default=datetime.date.today)),
                ('method', models.CharField(choices=[('call', 'Call'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('visit', 'Visit'), ('email', 'Email'), ('other', 'Other')], default='call', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_by_member', models.ForeignKey(blank=True, db_column='contacted_by_member_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.member')),
                ('visitor', models.ForeignKey(db_column='visitor_id', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='attendance.attendancevisitor')),
            ],
            options={
                'db_table': 'first_timer_contacts',
                'ordering': ['-contact_date'],
            },
        ),
    ]
